# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - experiment: null # needs command line override

rescaling: ratio 
results_file: smoothed  
ckpt_file: last.ckpt
num_eigenvalues: 50
max_n_seqs: 2_000_000
subsample: 0.1
random_traversal_neighborhood: 15
n_jobs: -1

